### ISSUE TITLE
Why retire the pinebook pro?

### ISSUE THREAD

**Issue by collinarnett** [cole-mickens/nixcfg#8]
I have a pinebook in my config, and admittedly this laptop is pretty difficult to use as a daily driver. The wifi cuts out pretty frequently and it's very slow but I love everything else about it. It's arm, unbranded, no fan and nixos works great.

I was looking at your configuration to give me some inspiration on making my PBP experience better and I noticed that you retired it. Any particular reason why?

**Comment by colemickens** [comment]
This is probably more info than you wanted, but...

1. I have more powerful `aarch64-linux` hardware to tinker with, and have generally lost interest in favor of `riscv64-linux`. (I have a `visionfive1` and `visionfive2`).
1. The trackpad, while more tolerable with libinput, still isn't great.
1. I've gotten used to HiDPI displays... and higher refresh - my current daily driver is a 120Hz/1600p display, and my current-1 was a 90Hz/1600p display. 
1. Simplicity, lord, I think I have concurrently had like 9+ SBCs, 4 laptops, a gaming rig, two dev phones, etc. It's just too much and I spread myself too thin trying to tinker with them and do other nixos/nixpkgs work. I'm currently doing the digital nomad thing, with just this ASUS G14 2022 (`zeph`) and am really delighted. Other than `raisin` and `xeep` which are now remote backup targets, I'm going to be decommissioning/selling my other devices.
1. It's in a better place now, presumably. Someone else wanted to tinker so I threw it in a box and shipped it to them.

**Comment by colemickens** [comment]
I've finally pushed a cleaned up readme and configs that reflect what I described.

Going to close this but feel free to re-open if you're curious about anything, follow-ups, etc. :)

**Comment by collinarnett** [comment]
Thank you for your detailed reply. This is exactly what I was looking for. I also have quite a few hardware projects and could use the cleanup myself :smile:
